<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <UserSecretsId>5a6db536-4d9e-4bfd-8006-85420b82f175</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
    <PackageReference Include="Blazor.Bootstrap" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Cloud5mins.ShortenerTools.Core.csproj" />
    <ProjectReference Include="..\ServiceDefaults\Cloud5mins.ShortenerTools.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>